// Shared mock data for the Atlas direction — also reused by Helm/Orbit.
const DATA = {
  user: { name: 'Alvar', email: 'alvar@alvarny.com' },
  date: 'Friday, May 8 2026',
  greeting: 'Friday',
  sites: [
    {
      id: 'alvarny', name: 'alvarny', tag: 'Personal',
      domain: 'alvarny.com', sub: 'apps.alvarny.com',
      blurb: 'Portfolio + app lifecycle hub. Quiet front, deep back.',
      stack: 'Next.js · Vercel · Supabase',
      visitors: 12480, visitorsΔ: '+8.2%',
      rev: 0, revLabel: '—',
      cost: 38.40,
      uptime: 99.98,
      requests: '1.4M / mo',
      apps: 9, apiDay: 142.3,
      spark: [22,24,21,25,28,27,30,33,29,32,36,40,38,41,44,46,42,48,52,49,55,58,54,60,62,58,64,66,70,72],
      ssl: 41, deploys: 12, deploy: '2h ago',
    },
    {
      id: 'studios', name: 'alvarny studios', tag: 'Web & Shop',
      domain: 'alvarnystudios.com', sub: 'projects.alvarnystudios.com',
      blurb: 'Marketing site funnels leads into the project portal.',
      stack: 'Astro · Cloudflare · Linear',
      visitors: 4820, visitorsΔ: '+22.4%',
      rev: 18450, revLabel: 'MRR',
      cost: 22.10,
      uptime: 99.94,
      requests: '380K / mo',
      apps: 4, apiDay: 86.0,
      spark: [12,14,11,16,15,18,17,20,22,21,24,26,23,28,30,29,32,33,35,38,36,40,42,40,45,48,46,50,52,55],
      ssl: 89, deploys: 6, deploy: '5d ago',
    },
    {
      id: 'labs', name: 'alvarny labs', tag: 'App Development',
      domain: 'alvarnylabs.com', sub: 'projects.alvarnylabs.com',
      blurb: 'R&D shopfront for native + AI app builds.',
      stack: 'SvelteKit · Fly · Postgres',
      visitors: 2140, visitorsΔ: '−3.1%',
      rev: 9200, revLabel: 'MRR',
      cost: 64.80,
      uptime: 99.86,
      requests: '210K / mo',
      apps: 3, apiDay: 312.5,
      spark: [40,42,39,44,42,40,38,36,40,42,38,35,38,40,36,33,38,36,32,35,38,34,30,33,36,32,28,30,32,28],
      ssl: 162, deploys: 3, deploy: '1d ago',
    },
  ],
  digest: {
    headline: 'Sonnet 5.5 ships extended thinking; an open-source coding agent crosses 70% on SWE-Bench.',
    paragraph: 'Anthropic shipped Claude Sonnet 5.5 with a tunable extended-thinking budget — early benchmarks suggest a real bump in long-horizon tasks. Meanwhile a small but well-built open-source agent edged past 70% on SWE-Bench Verified, mostly on better tool use rather than a smarter base model. Two tooling notes worth your time: Cursor finally added project-wide refactor previews, and a Vercel demo turned an entire Stripe checkout into an MCP server in a weekend.',
    items: [
      { src: 'Anthropic',  ttl: 'Sonnet 5.5 — extended thinking, 200k context, faster vision', when: '2h' },
      { src: 'arXiv',      ttl: 'Tool-Augmented Agents and the End of "Pure" Benchmarks', when: '6h', em: true },
      { src: 'Cursor',     ttl: 'Project-wide refactor previews land in 0.42', when: '8h' },
      { src: 'HN',         ttl: 'Show HN: a 700-line MCP server that wraps any REST API', when: '10h' },
      { src: 'Vercel',     ttl: 'AI SDK 5 — first-class streaming for tool calls', when: '14h' },
      { src: 'Substack',   ttl: 'Why "agent reliability" is the only metric that ships', when: '1d', em: true },
    ],
  },
  tickets: [
    { id: 'A-142', site: 'alvarny',  title: 'Replace homepage hero with kinetic type loop',
      preview: 'Idea: explore something more alive than the current static frame.',
      status: 'idea', raw: 'Hero feels static. Want a loop, calm, monochrome maybe.' },
    { id: 'A-141', site: 'studios',  title: 'Lead-form: pre-qualify by budget tier',
      preview: 'Three radios + conditional copy; route to right Linear queue.',
      status: 'prompt' },
    { id: 'A-140', site: 'labs',     title: 'Pricing: usage-based row for Claude API passthrough',
      preview: 'Show transparent margin, similar to Vercel pricing.',
      status: 'progress' },
    { id: 'A-139', site: 'alvarny',  title: 'apps.alvarny.com — per-app billing breakdown',
      preview: 'New tab on each app detail; pulls from Stripe metadata.',
      status: 'progress' },
    { id: 'A-138', site: 'studios',  title: 'Case study template + first 2 case studies',
      preview: 'Long-form, image-led, footnotes. Newsreader serif.',
      status: 'idea' },
    { id: 'A-137', site: 'labs',     title: 'Add status page (Atlassian-style) at status.alvarnylabs.com',
      preview: 'Connect to existing UptimeRobot probes.',
      status: 'shipped' },
    { id: 'A-136', site: 'alvarny',  title: 'Dark mode for /writing',
      preview: 'Match the site\u2019s warm gray; no toggle, follow system.',
      status: 'shipped' },
  ],
  costs: [
    { name: 'Vercel',     scope: 'alvarny + studios', cat: 'hosting',  m: 38.40 },
    { name: 'Cloudflare', scope: 'studios', cat: 'cdn/edge', m: 5.00 },
    { name: 'Fly.io',     scope: 'labs', cat: 'hosting',  m: 24.80 },
    { name: 'Supabase',   scope: 'alvarny', cat: 'database', m: 25.00 },
    { name: 'Postgres (Neon)', scope: 'labs', cat: 'database', m: 19.00 },
    { name: 'Anthropic API', scope: 'all sites', cat: 'ai', m: 312.40, isApi: true },
    { name: 'OpenAI API',    scope: 'labs', cat: 'ai', m: 48.20, isApi: true },
    { name: 'Resend',     scope: 'all sites', cat: 'email', m: 8.00 },
    { name: 'Linear',     scope: 'all sites', cat: 'tools', m: 16.00 },
    { name: 'Domain renewals (3)', scope: 'all sites', cat: 'domains', m: 2.40 },
  ],
  focus: [
    { t: 'Ship A-140 pricing row to staging', done: true },
    { t: 'Review labs case study draft (30m)', done: false },
    { t: 'Reply to 2 leads in studios inbox', done: false },
    { t: 'Read MCP server article on HN', done: false },
  ],
  signals: [
    { l: 'Visitors · 7d', v: '19,440', d: '+11%' },
    { l: 'Active leads', v: '7', d: '+3' },
    { l: 'Open tickets', v: '12', d: '−2' },
    { l: 'Spend · MTD', v: '$498', d: '+5%' },
  ],
  reading: [
    { src: 'arXiv',  ttl: 'Constitutional AI: a survey of 2024–2026 work' },
    { src: 'Stratechery', ttl: 'The post-LLM stack' },
    { src: 'Pragmatic Engineer', ttl: 'How small teams use Claude Code' },
  ],
};

// Naive "make it a Claude Code prompt" rewriter.
function toPrompt(raw, site, title) {
  const sitePath = { alvarny: '~/code/alvarny', studios: '~/code/alvarny-studios', labs: '~/code/alvarny-labs' }[site];
  return [
    `# Task: ${title}`,
    ``,
    `## Repo`,
    `${sitePath}`,
    ``,
    `## Context`,
    raw || '(no extra notes)',
    ``,
    `## Acceptance criteria`,
    `1. Implementation matches the description above.`,
    `2. Existing tests pass; add coverage for new behavior.`,
    `3. No new dependencies unless justified inline.`,
    `4. Open a PR titled "${title}" against \`main\` with a screenshot/loom in the body.`,
    ``,
    `## Constraints`,
    `- Match existing code style and component conventions.`,
    `- Do not modify unrelated files.`,
    `- If a decision is ambiguous, leave a // TODO(alvar) and surface it in the PR description.`,
  ].join('\n');
}

window.DATA = DATA;
window.toPrompt = toPrompt;
